theme = "ayu_dark"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
end-of-line-diagnostics = "hint"
cursorline = true
mouse = true
color-modes = true
auto-format = true

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "╎" "▏", "┆", "", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line="error"

[editor.whitespace]
#space = ""
# nbsp = "⍽"
# nnbsp = "␣"
tab = "→"
#newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.whitespace.render]
# space = "all"
tab = "all"
# nbsp = "all"
# nnbsp = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[keys.normal]
A-j = "jump_view_down"
A-k = "jump_view_up"
A-h = "jump_view_left"
A-l = "jump_view_right"
A-x = "extend_line_up"


[keys.normal.space.g]
b = [
  ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
]
 
[keys.normal.space.o]
e = [":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"]
b = [
  ":new",
  ":insert-output btop",
  ":theme default",
  ":buffer-close!",
  ":theme ayu_dark",
  ":redraw"
]
g = [
  ":new",
  ":insert-output lazygit",
  ":theme default",
  ":buffer-close!",
  ":theme ayu_dark",
  ":redraw"
]

j = [
  ":new",
  ":insert-output jjui",
  ":theme default",
  ":buffer-close!",
  ":theme ayu_dark",
  ":redraw"
]
