[[language]]
name = "dart"

[language.debugger]
name = "dart"
transport = "stdio"
command = "flutter"
args = [ "debug-adapter" ]

[[language.debugger.templates]]
name = "launch"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "lib/main.dart" } ]
args = { program = "{0}" }
