#!/bin/bash

installHyprland() {
    echo "Installing Hyprland dependencies"
    yay -S --asdeps hyprutils-git hyprlang-git hyprcursor-git hyprwayland-scanner-git

    yay -S xdg-desktop-portal-hyprland xdg-desktop-portal

    echo "\nInstalling Hyprland"

    yay -S hyprland-git

    yay -S wofi waybar kitty nwg-look dunst
}

installHyprland
