_G.nvim_start_time = vim.loop.hrtime()
require("config.lazy")
require("config.options")
require("config.mappings")
require("config.autocmds")
require("config.usercommands")
require("config.lsp")
require("config.jj").setup()
