return {
  "plugins.treesitter",
  "plugins.helpers",
  "plugins.mini",
  "plugins.colorschemes",
  "plugins.snacks",
  "plugins.which-key",
  "plugins.lualine",
  "plugins.supermaven",
  "plugins.flutter-tools",
  "plugins.edgy",
  "plugins.hunk",
  "plugins.undotree",
  "plugins.baleia",
  -- "plugins.avante",
  "plugins.org",
  "plugins.tabby",
  "plugins.dap",
  "plugins.blink",
  "plugins.smearcursor",
}
